# Site Settings
name: ICER233'S BLOG
title: ICER233'S BLOG
description: ICER233'S BLOG
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: "主页"
    url: /
  - title: "SB语录"
    url: /SB-Quotation
  - title: "留言"
    url: /contact
  - title: "标签"
    url: /tags
email: tommydai0909@163.com
# See: https://disqus.com/
disqus_username: 
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: 


# Social Media Settings
# Remove the item if you don't need it
github_username: icer233

# Posts Settings
show_time_bar: false
show_modal_on_exit: false
show_modal_on_finish_post: false
two_columns_layout: false


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v11.4.514

translations:
  text:
    new_post: "新帖"
    see_also: "再看看……"
    search: "搜索"
    author: "作者"
    share: "分享"
    comments: "评论"
  button:
    read_now: "开始阅读"
    share_on_twitter: "分享到Twitter"
    share_on_facebook: "分享到Facebook"
  pagination:
    page: "页码："
    of: "共"
    next_page: "下一页"
    next_post: "上一页"
  recommendation:
    text: "接下来为什么不再读点什么？"
    back_btn: "回到顶部"
  error_404:
    title: "页面未找到 :("
    message: "抱歉，未找到您所访问的页面"
    image_alt: "404 - 页面未找到"
  contact:
    title: "和我说说"
    subject: "新的联系！"
    submit_btn: "发送"
    placeholders:
      name: "你的姓名"
      email: "你的邮箱"
      message: "你的信息"
    errors:
      locale: "cn"
      empty_name: "姓名是必须的"
      empty_email: "邮箱是必须的"
      invalid_email: "邮箱不合法"
      empty_message: "信息是必需的"
    after_send:
      title: "信息已发送！"
      message: "感谢您给我发信息，我会尽快回复。"